version: "3.7"

services:
  app:
    container_name: dashboard-dev
    image: dashboard-dev
    build:
      context: .
      dockerfile: ./dev/Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
